### PR TITLE
fixed http://self authority

### PR DESCRIPTION
**Pull request by thesuhas**
Fix for https://github.com/fermyon/spin-python-sdk/issues/107

### CODE REVIEW

**Review by dicej — APPROVED** [review]
Thanks so much for reporting and fixing this, @thesuhas !

**Comment by thesuhas** [comment]
I just pip installed spin-sdk and I see that this bug still exists, I'm assuming it's because the python package was not updated because of an updated version of the code?

**Comment by dicej** [comment]
Correct.  I'll go ahead and publish a new release.

**Comment by dicej** [comment]
Done: https://pypi.org/project/spin-sdk/3.2.1/

**Pull request merged**
