### PR TITLE
add docs

### PR DESCRIPTION
**Pull request by dicej**
This adds a set of stub modules which mirror the API generated from `spin-python-engine`'s Rust code by PyO3, from which we can generate HTML documentation to host on GitHub Pages.  Ideally, we'd generate those docs from the Rust code using some combination of `PyO3` and `maturin`, but I'm not sure how to do that, and we're planning to deprecate this whole project in favor of `componentize-py` and a new SDK based on it, so I went the easy route.

Note to reviewers: the HTML files are generated automatically from the .py files, so don't bother looking at those.

### CODE REVIEW

**Comment by karthik2804** [comment]
@dicej , we probably want to get rid of the `spin_sdk` inside `docs` and just be `docs/index.html` as when served from github pages, the `/docs` will be the root.

**Comment by dicej** [comment]
> @dicej , we probably want to get rid of the `spin_sdk` inside `docs` and just be `docs/index.html` as when served from github pages, the `/docs` will be the root.

Ah, so we can't point it at `/docs/spin_sdk`?

**Review by itowlson — APPROVED** [review]
LGTM - thanks for cranking this out @dicej (and @karthik2804 for help!)

**Comment by karthik2804** [comment]
@dicej GH lets us use either `/` or `/docs` - it is not very flexible.

**Review by karthik2804 — APPROVED** [review]
LGTM!

**Pull request merged**
