### PR TITLE
Update app.py

### PR DESCRIPTION
**Pull request by sohanmaheshwar**
The previous dog-facts API was not working.

Updated code to include working API. This API returns animal facts and not only dog facts. 

See GH issue here: https://github.com/fermyon/developer/issues/692

### CODE REVIEW

**Comment by mikkelhegn** [comment]
Thx @sohanmaheshwar, you will have add the new url endpoint to the `[allowed_http_hosts]` array in the manifest `spin.toml`. https://developer.fermyon.com/spin/manifest-reference#the-component-tables

**Review by mikkelhegn — APPROVED** [review]
LGTM

**Comment by mikkelhegn** [comment]
@sohanmaheshwar - You'll need to sign-off the commits `git commit -sS`

**Comment by sohanmaheshwar** [comment]
Phew. Took a couple of attempts, but finally the PR is verified with my GPG key.

**Review by karthik2804 — APPROVED** [review]

**Review by dicej — APPROVED** [review]

**Pull request closed without merging**
