### PR TITLE
bump version to 0.3.2

### PR DESCRIPTION
**Pull request by dicej**

### CODE REVIEW

**Review by karthik2804 — APPROVED** [review]
Not blocking but is there a reason we are bumping patch instead of minor?

**Comment by dicej** [comment]
> Not blocking but is there a reason we are bumping patch instead of minor?

AFAIK we haven't made any breaking changes, and I'm following the Rust style semver convention that pre-1.0 minor version bumps mean breaking changes.

**Comment by karthik2804** [comment]
@dicej we also need to bump the spin compatibility version in `manifest/spin-compat`. It is currently pointing at 0.9 but llms need 1.5.

**Review by karthik2804 — APPROVED** [review]
LGTM! Thanks

**Comment by dicej** [comment]
Ok, updated the spin compat version and updated the SDK version again to 0.3.2 since I already tagged 0.3.1.

**Comment by karthik2804** [comment]
We need to merge before the tag so that CI, picks up the version changes for both the binary and plugin package.

**Comment by dicej** [comment]
We should probably add a `Releasing` section to README.md that documents the release process.  Clearly I've forgotten.

**Pull request merged**
